behaviors:
  Bridge:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0  
      curiosity:
        gamma: 0.99
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
      gail:
        gamma: 0.99
        strength: 0.5
        demo_path: Project/Demos/Bridgetest5_0.demo
    keep_checkpoints: 50
    max_steps: 5000001
    time_horizon: 64
    summary_freq: 10000

