behaviors:
  BridgeCooperative_1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 1.0
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 1.0
        demo_path: Project/Demos/multiBridgeGAIL_1.demo
    behavioral_cloning:
      demo_path: Project/Demos/multiBridgeGAIL_1.demo
      strength: 1.0
      steps: 150000
    keep_checkpoints: 50
    max_steps: 21000001
    time_horizon: 64
    summary_freq: 60000
  BridgeCooperative_2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 1.0
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 1.0
        demo_path: Project/Demos/multiBridgeGAIL_2.demo
    behavioral_cloning:
      demo_path: Project/Demos/multiBridgeGAIL_2.demo
      strength: 1.0
      steps: 150000
    keep_checkpoints: 50
    max_steps: 21000001
    time_horizon: 64
    summary_freq: 60000
