behaviors:
  Push:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 50
    max_steps: 5000001
    time_horizon: 64
    summary_freq: 60000
environment_parameters:
  distance_offset:
    curriculum:
      - name: Lesson0 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Push
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.3
        value: 0.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: Push
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.6
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0
            max_value: 0.2
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Push
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.4
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.2
            max_value: 0.5
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Push
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.5
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.5
            max_value: 0.8
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: Push
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.7
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.8
            max_value: 1
      - name: Lesson5
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0
            max_value: 1
