behaviors:
  Parkour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.90
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0  
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003
      gail:
        strength: 0.0
        demo_path: Project/Demos/ParkourRayHard.demo
        use_actions: true
    keep_checkpoints: 5
    max_steps: 5000001
    time_horizon: 1000
    summary_freq: 30000
    threaded: true